### ISSUE TITLE
Feature Request: include full request URL in parameters

### ISSUE THREAD

**Issue by getify** [anseki/node-static-alias#3]
It would be helpful to additionally have the full request URL (as exposed by `req.url`, like `/foo/bar/baz.jpg?bam=1`) available in the "Parameters" that are accessible for matching, both in the string (`key=value`) form and in the function form. Of course, it should also be available for the serve specification, like `<% ... %>`. I propose this new parameter be called "reqURL" to fit with "reqPath" and others.

I had a use-case where I wanted to serve a different file depending on if there was a `?SID=...` query parameter in the URL. I had to work-around the lack of that information available for matching by pre-parsing `req.url` and manually overriding it, before calling `serve(..)`.

**Comment by anseki** [comment]
Thank you for the proposal.
I will look into that when I have time.

For the moment, you can specify a function (that checks `req.url`) for `match` property of an Alias-Rule Object.

**Comment by getify** [comment]
How do I access `req` from that function?

**Comment by anseki** [comment]
For example:
```js
require('http').createServer((request, response) => {

  const fileServer = new (require('node-static-alias')).Server('./public', {
    alias: {
      match: () => /\bKEY=A\b/.test(request.url),
      serve: 'a.html'
    }
  });

  request.addListener('end', () => {
    fileServer.serve(request, response);
  }).resume();
}).listen(8080);
```

When you access to http://localhost:8080/?KEY=A, a file `a.html` is served.

**Comment by getify** [comment]
Oh... you're setting up a whole new instance for each request? Isn't that awfully inefficient? I have only ever set up one instance to share for all requests.

**Comment by anseki** [comment]
Of course `request` instance and `response` instance also are created for each request.
And node-static and node-static-alias are very small.

If you really want to share that for all requests, just move the constructor from the listener.
For example:
```js
let url;
const fileServer = new (require('node-static-alias')).Server('./public', {
  alias: {
    match: () => /\bKEY=A\b/.test(url),
    serve: 'a.html'
  }
});

require('http').createServer((request, response) => {
  url = request.url;

  request.addListener('end', () => {
    fileServer.serve(request, response);
  }).resume();
}).listen(8080);
```

**Comment by anseki** [comment]
I updated it.
Now, you can specify `query_SID=...` to `match` property, to check `SID` query parameter.
Also, you can access to `request` and `response` via arguments if you want.

**Comment by anseki** [comment]
This feature was already implemented, and I close this issue.
