### ISSUE TITLE
Feature Request: support asynchrony for `match(..)` / `serve(..)` handler functions

### ISSUE THREAD

**Issue by getify** [anseki/node-static-alias#4]
Both `match(..)` and `serve(..)` expect an immediate return value.

But would you consider a minimal modification (not a breaking change, I don't think) where if either returns a promise, it's waited on to resolve before moving on?

For example:

```js
// ..
{
   async match(params,req,res) {
      var result = await Router.check(params.reqUrl);
      if (url) return true;
      else return false;
   },
   async serve(params,req,res) {
      let reqBody = JSON.parse(await getStream(req));
      if (reqBody.addExtension) return params.reqPath + ".html";
      else return params.reqPath;
   }
}
// ..
```

In this contrived example, matching (`true` / `false`) is asynchronous because the router may be looking up a route from a database or other async persistence layer, and serving is asynchronous because it needs to read something from the request-body (retrieved asynchronously) to decide what filename to use.

Right now, I'm having to do this kind of stuff as pre-processing, doing the asynchronous waiting and adding properties to the `req` object, all before calling node-static-alias. It would be nice if that async logic could just be embedded into `match(..)` / `serve(..)`.

I think all that needs to happen is that those handlers need to see if a promise is returned, and if so, simply call `then(..)` on it to wait. I don't think returning a promise would have been valid prior, so this doesn't seem like a breaking change.

**Comment by anseki** [comment]
Hi @getify, thank you for the proposal.

So, I think that the feature is not needed because the [`http`](https://nodejs.org/api/http.html) module of Node.js already supports asyn-mode. Strictly speaking, that works only in asyn-mode, it does not work in sync-mode.

Important point, the `alias.match` and `alias.serve` properties do not match the file and not serve that. These tell the file which must be served to "node-static" (i.e. `http`). The `serve` method of "node-static" (i.e. `stream.write`) serves that, not `alias.serve`.

Therefore, you can call `serve` method (not `alias.serve`) when it is ready.
For example:

```js
const result = await Router.check(params.reqUrl); // Do something asynchronously.
// Do something to prepare `alias`.
alias.serve = result.foo ? 'FILE-A.html' : 'FILE-B.html';
fileServer.serve(request, response);
```

Your script doesn't work asynchronously even if this feature was implemented because `serve` method (not `alias.serve`) doesn't wait for those to return.

**Comment by getify** [comment]
Yeah, I'm already delaying before calling `fileServer.serve(..)`, which operates fine but is not a desirable approach.

For code clarity/organization/style reasons, I would prefer to be able locate the async logic inside of `alias.match(..)`/ `alias.serve(..)`, which are invoked **after** having called `fileServer.serve(..)`.

Moreover, this change would be helpful for performance reasons. In my current setup, I am doing this async lookup of a cookie value; that lookup is only relevant to some of my alias routes, not all of them. However, since I'm having to do the async-look before calling `fileServer.serve(..)`, that lookup is happening for all requests, meaning all of them are slightly delayed (even just regular static files like .css files etc).

Of course, I could wrap some conditional logic around that prior async-lookup logic to do it only for some request paths... BUT that's the whole point of using node-static-alias, to handle the matching -- inventing my own matching conditional logic kind of defeats the whole point of using this library.

It clear that the design of this library currently is that matching and serve-path-resolution are fundamentally synchronous actions. But I would argue that it would make the library more powerful if you allowed asynchronous matching / path-resolution, which is what I'm proposing.

**Comment by getify** [comment]
FYI, I've forked this library and implemented the async handling I'm suggesting. It took a fair bit of effort to reconfigure the `.some(..)` synchronous iteration that's currently used, and make it capable of asynchronous-iteration. But it seems to be working in my limited tests so far.

Here's that fork:

https://github.com/getify/node-static-alias/commit/60814be3085ade93fcbd387d0030196f46b20560

Would you mind taking a look and see if you think this is a feature improvement you'd consider accepting a PR for?

**Comment by anseki** [comment]
Thank you for the explanation.
However, sorry, I can't understand that merit yet.
And I am concerned about the different behavior only when it is a function.
node-static-alias tells the file which must be served to node-static. That should have style like "Declarative Style", not "Procedural Style".
Basically, the `alias` should be like this:

```js
alias: {
  match: '/path/to/fileA',
  serve: '/path/to/fileB'
}
```

A function is a complementary method that can be used to decide the value when run-time. Therefore, that should not change the behavior.
And also, the feature is not needed because that does nothing until `serve` method is called. That is, it already works asynchronously.

Sorry if I misunderstood your comment because my English is poor.

BTW, unfortunately your code didn't pass some tests for `Server.prototype.parsePath`, and ESLint warned about syntax. I didn't look in detail, at least the code should be written in ES5 (not ES2015), at the moment.
Of course these are meaningless if you use your forked code in your project.

**Comment by getify** [comment]
> And I am concerned about the different behavior only when it is a function.

It's not "different" behavior. It's still allowing you to use a function to determine if there's a match or not, or use a function to compute the resolved path. It's just that the logic for determining the match or computing the path might be asynchronous instead of synchronous.

> A function is a complementary method that can be used to decide the value when run-time. Therefore, that should not change the behavior.

Yes, I agree, and what I'm saying is, sometimes that run-time decision is not able to be determined synchronously, it needs to be done asynchronously.

----

> the feature is not needed because that does nothing until serve method is called.

Yes, I get what you're saying -- you just want me to do the async logic **before** calling `fileServer.serve(..)`. But you're missing what I'm saying about why that is not a good solution:

1. If I do the async logic **before** calling `fileServer.serve(..)`, that means **all** inbound requests are being "delayed" by the async logic. However, my asynchronous logic should only impact SOME of the alias routes/requests. Consider:

   ```js
   // alias
   {
      match: "/foo",
      serve: function(params,req,res) {
         if (req.someFlag) return "bar.html";
         else return "foo.html";
      }
   }

   // ..

   // this `await` async check delay is going to run for EVERY SINGLE REQUEST,
   // even though it's only relevant and needed for "/foo" requests. This is bad. :(
   var check = await doSomeAsyncCheck(req.url);
   if (check) req.someFlag = true;
 
   fileServer.serve(req,res);
   ```

   Do you see why this is bad? That async delay (from the `await`) is impacting every single request, not only the "/foo" requests as desired.

2. If I do the async logic **before** calling `fileServer.serve(..)`, but want it to only affect certain aliases/requests, it means I have to duplicate the conditional matching logic (imperatively, not declaratively), like:

   ```js
   // alias
   {
      match: "/foo",
      serve: function(params,req,res) {
         if (req.someFlag) return "bar.html";
         else return "foo.html";
      }
   }

   // ..

   if (req.url == "/foo") {
      // now this check only happens for "/foo" requests, which is better.
      // but it's bad that I had to duplicate the matching logic with this "if"
      // statement. :(
      let check = await doSomeAsyncCheck(req.url);
      if (check) req.someFlag = true;
   }
 
   fileServer.serve(req,res);
   ```

   Do you see how I've had to duplicate the matching of "/foo" here? I have it once in the declarative alias list, and a second time imperatively in the `if` statement. This is undesirable.

   The whole reason I'm using node-static-alias is because I want to rely on the declarative matching logic, so I don't want to duplicate that code **before** `fileServer.serve(..)`. I instead want to locate my async checking logic inside the `alias.match(..)` or `alias.serve(..)` methods, so that the declarative matching that node-static-alias performs is still used.

3. So, I think the best answer to these problems is for the async checking delay to happen **after** calling `fileServer.serve(..)`, inside of `alias.serve(..)`. In other words, this approach solves the issues:

   ```js
   // alias
   {
      match: "/foo",
      serve: async function(params,req,res) {
         let check = await doSomeAsyncCheck(req.url);

         if (check) return "bar.html";
         else return "foo.html";
      }
   }

   // ..
 
   fileServer.serve(req,res);
   ```

   Do you see why that's more preferable? It's still declarative, doesn't duplicate matching logic, but is more performant in that the async check only happens for that one alias and not for all requests?

----

> unfortunately your code didn't pass some tests for Server.prototype.parsePath, and ESLint warned about syntax. I didn't look in detail, at least the code should be written in ES5 (not ES2015), at the moment.

I don't mind changing the syntax of the code before doing a PR. I'm just using ES6 for now since that makes certain coding much cleaner (simple destructuring, `...` spread/gather, etc).

But, I'm not sure why you're requiring ES5 code? This project only runs in Node, which is currently on v10 -- Node had [nearly complete ES2015/ES6 support way back in Node v6.4](https://node.green/), approximately 2 years ago. And many of the ES6 features were actually supported much earlier.

Surely you don't need to keep supporting such old Node versions, right?

**Comment by getify** [comment]
> However, sorry, I can't understand that merit yet.

Would it help if we got on a live chat (google hangouts, skype, slack, etc) so I could try to explain better? Happy to do so.

For now, let me attempt to show you an example from my code to illustrate the merits:

```js
{
   match: "/foo",
   serve: async function(params,req,res) {
      if (/super-secret/.test(req.headers.cookie || "")) {
         let secretPath = await lookupPathInDatabase(req);
         return secretPath;
      }
      else return "foo.html";
   }
},
{
   match: "/bar",
   serve: "bar.html"
},
{
   match: async function(params,req,res) {
      if (req.url == "/baz") {
         let isAllowed = await checkPermissions(req);
         return isAllowed;
      }
      return false;
   },
   serve: "baz.html"
},
{
   match: /[^]/,
   serve: "404.html"
}

// ..

fileServe.serve(req,res);
```

OK, so let me explain what's going on here.

1. Requests for "/foo" should normally serve "foo.html". However, if there's a cookie called "super-secret" passed for this request, then an alternate serve path is looked up in the database and used.

   This database lookup is **async**. But it only needs to happen for "/foo" requests.

2. Requests for "/bar" always just serve "bar.html", nothing special here. Importantly, these requests should not be affected by async lookup delays happening for either of the other request routes.

3. Requests for "/baz" are only matched (allowed) if an async permissions check passes based on the cookies/headers in the request. Otherwise, that alias isn't matched.

   This permissions lookup is **async**. But it only needs to happen for "/baz" requests.

----

Here's the old way which I am arguing is far less desirable (for all the reasons previously discussed):

```js
{
   match: "/foo",
   serve: function(params,req,res) {
      if (req.secretPath) {
         return req.secretPath;
      }
      else return "foo.html";
   }
},
{
   match: "/bar",
   serve: "bar.html"
},
{
   match: function(params,req,res) {
      return !!req.isAllowed;
   },
   serve: "baz.html"
},
{
   match: /[^]/,
   serve: "404.html"
}

// ..

if (
   req.url == "/foo" &&
   /super-secret/.test(req.headers.cookie || "")
) {
   let secretPath = await lookupPathInDatabase(req);
   req.secretPath = secretPath;
}
if (req.url == "/baz") {
   let isAllowed = await checkPermissions(req);
   req.isAllowed = isAllowed;
}

fileServe.serve(req,res);
```

As you can see, this version is much more imperative. It's a very undesirable style/approach IMO, compared to my proposed feature capability.

**Comment by getify** [comment]
> unfortunately your code didn't pass some tests for Server.prototype.parsePath

Can you share which tests these are? I'd like to fix. The goal of my code is to be 100% backwards compatible, so all previous tests should pass.

**Comment by anseki** [comment]
This your code:

```js
// alias
{
   match: "/foo",
   serve: function(params,req,res) {
      if (req.someFlag) return "bar.html";
      else return "foo.html";
   }
}

// ..

if (req.url == "/foo") {
   // now this check only happens for "/foo" requests, which is better.
   // but it's bad that I had to duplicate the matching logic with this "if"
   // statement. :(
   let check = await doSomeAsyncCheck(req.url);
   if (check) req.someFlag = true;
}

fileServer.serve(req,res);
```

can be replaced with:

```js
alias = req.url === '/foo' ? {
  match: () => true,
  serve: (await doSomeAsyncCheck(req.url)) ? 'bar.html' : 'foo.html'
} : null;
fileServer.serve(req, res);
```

As I said, that should not change the behavior.
You said that this feature doesn't change the behavior, but I can not agree with you on that point. At least, that makes it work asynchronously, this is a clear difference.

**Comment by getify** [comment]
> can be replaced with:

No it cannot, because you're defining the alias at runtime (per request), and I'm defining the whole list of alias routes once at the beginning of the server. These are "clearly different". It's not acceptable (either performance or code style) to me to define alias routes dynamically. My whole goal is to have them declaratively written out in a configuration part of my code base, not embedded imperatively inside the HTTP request handler.

----

I'm not looking for other ways to hack or work-around. There's a million ways to work-around limitations of some library. I already have plenty of options, none of which I prefer.

What I'm trying to get at is that I find it useful, and non-hacky, to be able to contain the asynchrony in the `alias.match(..)` / `alias.serve(..)`. If you don't agree, OK, I guess that's my answer. But I really was hoping you would see why it's helpful.

> At least, that makes it work asynchronously, this is a clear difference.

Well, we'll just disagree then.

If you pass a regular function (that doesn't return a promise) as `alias.match(..)` / `alias.serve(..)`, those **still function synchronously**. It's just providing an option for someone to make one of them pause and finish asynchronously if they want.

That's very non-intrusive to existing users of this library, in that it would literally have zero difference behaviorally or performance wise to any existing code. It's purely an augmentation of capability for some (like me) who would like to use it.

Moreover, conceptually, promises are all about encapsulating time (sync vs async) and giving you a value primitive that operates in a time-independent way. I didn't change any of the signature of node-static-alias, nor change any of the behavior or performance of existing sync usages of the library.

To me, that's less "clearly different" than it seems like you're interpreting. Anyway, thanks for your consideration.

**Comment by anseki** [comment]
You can access an element in an Array via `array[index]`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
Therefore, if you want to update the element in the list of alias that was already defined, you can do that via the index.

```js
const
  aliasList = [
    // for other files
    {match: ..., serve: ...},
    {match: ..., serve: ...},
    {match: ..., serve: ...},
    // for `/foo`
    {},
    // for other files
    {match: ..., serve: ...},
    ...
  ],
  fileServer = new staticAlias.Server('./public', {alias: aliasList});

// Init Server, etc...

req.addListener('end', () => {
  aliasList[3] = req.url === '/foo' ? {
    match: () => true,
    serve: (await doSomeAsyncCheck(req.url)) ? 'bar.html' : 'foo.html'
  } : {match: []};
  fileServer.serve(req, res);
}).resume();
```

Or, you can also use a reference to the element instead of the index.

```js
let matched;
const
  aliasForFoo = {match: () => matched},
  aliasList = [
    // for other files
    {match: ..., serve: ...},
    {match: ..., serve: ...},
    {match: ..., serve: ...},
    // for `/foo`
    aliasForFoo,
    // for other files
    {match: ..., serve: ...},
    ...
  ],
  fileServer = new staticAlias.Server('./public', {alias: aliasList});

// Init Server, etc...

req.addListener('end', () => {
  if ((matched = req.url === '/foo')) {
    aliasForFoo.serve = (await doSomeAsyncCheck(req.url)) ? 'bar.html' : 'foo.html';
  }
  fileServer.serve(req, res);
}).resume();
```

Usually, an API like this feature is not good API that the behavior is changed by the option for configuration only in specific case. These lack uniformity.
I looked at some major libraries, but I could not find out a library that has API that a function that is a complementary method for configuration changes the behavior only when the function returned specific value. (Of course that might exist.)
In standard API, that configuration should have style like "Declarative Style". A function is a complementary method. That should not change the behavior only in special cases.

Anyway, there are points:

- I agree that this feature might be helpful in specific cases if you want to write those procedures in the configuration.
- I think that you agree that the feature is not really needed because other simple ways such as the examples I indicated can be used instead.
- I think that you agree that the feature changes the behavior in specific cases.

Then, I think now that:

- A library should have standard API.
- I want to keep the code simple.
- I want to keep the API simple.
- However I rethink when more request came.

Thank you for the proposal and the explanation.
I couldn't explain well because my English is poor, but you explained very patiently. Thank you :smile:

BTW, the `match` accepting a boolean might be helpful.

**Comment by getify** [comment]
For the approaches you're suggesting, where you're re-defining the alias entries as each request comes in, I think this is almost certainly going to introduce race conditions, where the state of that shared global aliases list changes half-way through because a second request comes in while the first request is still asynchronously processing through the list.

I would be very skeptical to put an approach like that into production. Side effects and state changing unpredictably over time are the root of all programming evil, IMO. :)

> I think that you agree that the feature is not really needed because other simple ways such as the examples I indicated can be used instead.

Eh. Needed? Yes. Absolutely necessary? Perhaps not.

I'd say it's needed enough that my plan is to continue using a forked version of this lib instead of one of these other workaround ways.

My fork seems to be doing well for my needs. I really like having `alias.match(..)` / `alias.serve(..)` encapsulate the asynchrony cleanly, and so it's worth it to me to just stay forked.

Of course, I'd rather just have that capability be folded into the main lib, so if that ever happens, great. ;-)

**Comment by anseki** [comment]
If the `doSomeAsyncCheck` calls `nextTick`, you can use this instead of the example above:

```js
req.addListener('end', () => {
  matched = false;
  if (req.url === '/foo') {
    aliasForFoo.serve = (await doSomeAsyncCheck(req.url)) ? 'bar.html' : 'foo.html';
    matched = true;
  }
  fileServer.serve(req, res);
}).resume();
```

**Comment by anseki** [comment]
No reply came. I close this issue.
